# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  workflow_dispatch:

  schedule:
# run daily at 00:00
    - cron:  '0 0 * * *'
 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js 22.x
      uses: actions/setup-node@v4
      with:
        node-version: 22.x
        cache: 'npm'
        
#download https://www.1823.gov.hk/common/ical/en.json to en.json
    - name: Download en.json
      run: curl -o en.json https://www.1823.gov.hk/common/ical/en.json

#push to en.json to repo
    - name: Push changes to repo
      run: |
        git config --local user.email "41898282+github-actions[bot]"@users.noreply.github.com"
        git config --local user.name "github-actions[bot]"
        git add en.json
        git commit -m "Update en.json"
        git push


      



